<script src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<form id="acceptanceFrom" action="<?php echo APP_CTX?>/widget/invitation/confirmation" method="post">
	<div>Accpetance</div>
	<div>Send to <?php echo $this->name?></div>
	<div>Free Call Dur: <?php echo $this->freeCallDur?></div>
	<div>Charge Amount: <?php echo $this->chargeAmount?></div>
	<div>Min Call Blk Dur: <?php echo $this->minCallBlkDur?></div>
	<div>
		<input type="submit" id="agreeButton" value="<?php echo MultiLang::getText("SEND_INVITATION", $country)?>" disabled />
	</div>
	<div>
		<input type="checkbox" id="agreeCheckbox" tabindex="1" onclick="checkAgree('#agreeCheckbox', '#agreeButton')"/>I agree
		<small id="agreementInvalid" style="display:none">
			agreement invalid
		</small>
	</div>
</form>
