<script src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<form id="acceptanceFrom" action="<?php echo APP_CTX?>/widget/invitation/confimation" method="post" onsubmit="submiteAnonCall('#acceptanceFrom'); return false;">
	<div>Accpetance</div>
	<div>Send to <?php echo $this->name?></div>
	<div>Free Call Dur: <?php echo $this->freeCallDur?></div>
	<div>Charge Amount: <?php echo $this->chargeAmount?></div>
	<div>Min Call Blk Dur: <?php echo $this->minCallBlkDur?></div>
	<div>
		<input type="submit" value="<?php echo MultiLang::getText("SEND_INVITATION", $country)?>" />
	</div>
	<div>
		<input type="checkbox" name="agreement" tabindex="1" />I agree
		<small id="agreementInvalid" style="display:none">
			agreement invalid
		</small>
	</div>
	
</form>
