<script type="text/javascript" src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<form action="<?php echo APP_CTX?>/widget/invitation/confirmation" method="post">
	Confirmation Screen
</form>
<script type="text/javascript">
function toglePayType(payType) {
	if (payType == 0) {
		$("#selfPayInfo").attr("style", "display:none");
	} else {
		$("#selfPayInfo").attr("style", "display:block");
	}
}
</script>