<script type="text/javascript" src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<h1><?php echo MultiLang::getText("Invite_Someone_to_a_Tokumei_Call", $country)?></h1><br>
<form id="invitationFrom" action="<?php echo APP_CTX?>/widget/invitation/validate" method="post" onsubmit="submiteAnonCall('#invitationFrom'); return false;">
	<h3><?php echo MultiLang::getText("Enter_your_name", $country)?></h3>
	<div>
		<input value="Daniel" type="text" name="inviterName" placeholder="<?php echo MultiLang::getText("Name", $country)?>" tabindex="1" />
		<small id="inviterNameNotNull" style="display:none">
			<?php echo MultiLang::getText("Name", $country)?><?php echo MultiLang::getText("not_null", $country)?>
		</small>
	</div><br>
	<h3><?php echo MultiLang::getText("Enter_your_phone_number", $country)?></h3>
	<h4><?php echo MultiLang::getText("This_number_will_be_kept_private", $country)?></h4>
	<div>
		<input value="12176507163" type="text" name="inviterPhoneNumber" onkeypress="inputCheck('[0-9]', event)" placeholder="<?php echo MultiLang::getText("Phone_number", $country)?>" tabindex="1" />
		<small id="inviterPhoneNumberInvalid" style="display:none">
			<?php echo MultiLang::getText("Phone_number", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
		</small>
	</div><br>
	<h3><?php echo MultiLang::getText("Enter_their_email_address", $country)?></h3>
	<div>
		<input value="imddl137@gmail.com" type="text" name="inviteeEmail" placeholder="<?php echo MultiLang::getText("Email_address", $country)?>" tabindex="1" />
		<small id="inviteeEmailInvalid" style="display:none">
			<?php echo MultiLang::getText("Email_address", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
		</small>
	</div><br>
	<h3><?php echo MultiLang::getText("Enter_message", $country)?></h3>
	<div>
		<input type="text" name="inviteMsg" placeholder="<?php echo MultiLang::getText("message", $country)?>" tabindex="1" />
	</div><br>
	<div class="radioblock">
		<input type="radio" name="payType" value=0 onclick="toglePayType(0);" tabindex="1" checked><?php echo MultiLang::getText("Pay_by_the_other_side", $country)?><br>
		<input type="radio" name="payType" value=1 onclick="toglePayType(1);" tabindex="1"><?php echo MultiLang::getText("Pay_by_yourself", $country)?>
	</div>
	<div id="selfPayInfo" style="display:none">
		<div>
			<input type="text" name="creditCardNumber" onkeypress="inputCheck('[0-9]|\-', event)" placeholder="<?php echo MultiLang::getText("Credit_Card_Number", $country)?>" tabindex="1" /><br>
			<input type="twothird" name="creditCardExp" onkeypress="inputCheck('[0-9]|\/', event)" placeholder="<?php echo MultiLang::getText("Exp", $country)?>" tabindex="1" />
			<input type="fourth" name="creditCardCvc" onkeypress="inputCheck('[0-9]', event)" placeholder="<?php echo MultiLang::getText("CVC", $country)?>" tabindex="1" />
			<small id="creditCardInfoInvalid" style="display:none">
				<?php echo MultiLang::getText("Credit_Card_Information", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
			</small>
			</div><br>
		<div>
			<input type="text" name="inviterEmail" placeholder="<?php echo MultiLang::getText("Email_address", $country)?>" tabindex="1" />
			<small id="inviterEmailInvalid" style="display:none">
				<?php echo MultiLang::getText("Email_address", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
			</small>
		</div>
	</div><br>
	<div>
		<input type="submit" value="<?php echo MultiLang::getText("Send_inviation", $country)?>" />
	</div>
	<input type="hidden" name="partnerInx" value="<?php echo $this->partnerInx?>" />
</form>
<script type="text/javascript">
function toglePayType(payType) {
	if (payType == 0) {
		$("#selfPayInfo").attr("style", "display:none");
	} else {
		$("#selfPayInfo").attr("style", "display:block");
	}
}
</script>