<script src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<form id="invitationFrom" action="<?php echo APP_CTX?>/widget/invitation/invitation-validate" method="post" onsubmit="submiteAnonCall('#invitationFrom'); return false;">
	<div>
		<input value="imddl137@gmail.com" type="text" name="inviterEmail" placeholder="<?php echo MultiLang::getText("Email_address", $country)?>" tabindex="1" />
		<small id="inviterEmailInvalid" style="display:none">
			<?php echo MultiLang::getText("Email_address", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
		</small>
	</div>
	<div>
		<input value="17023580286" type="text" name="inviterPhoneNumber" onkeypress="inputCheck('[0-9]', event)" placeholder="<?php echo MultiLang::getText("Phone_number", $country)?>" tabindex="1" />
		<small id="inviterPhoneNumberInvalid" style="display:none">
			<?php echo MultiLang::getText("Phone_number", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
		</small>
	</div>
	<div>
		<input value="imddl4g@gmail.com" type="text" name="inviteeEmail" placeholder="<?php echo MultiLang::getText("Email_address", $country)?>" tabindex="1" />
		<small id="inviteeEmailInvalid" style="display:none">
			<?php echo MultiLang::getText("Email_address", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
		</small>
	</div><br>
	<div>
		<input type="submit" value="<?php echo MultiLang::getText("CONTINUE", $country)?>" />
	</div>
</form>
