<p> Credit card information </p>

<form action="/a/default/test/createCreditCard">
First Name <input name="first_name" value="Joe">
Last Name <input name="last_name" value="Shopper">
<br>
Card Type <input name="cc_type" value="visa">
Card Number <input name="cc_number" value="4417119669820331">
Expire Month <input name="cc_expire_month" value="11">
Expire Year <input name="cc_expire_year" value="2019">
Cvv <input name="cc_cvv" value="012">
<button>Save Credit Card Info</button>
</form>

<br><br>
<form action="/a/default/test/charge">
Card ID: $<input name="card_id" value="">
Charge Amount: $<input name="amount" value="2">
<button>Charge</button>
</form>

<hr>