<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2><hr />

<?php if ('development' == APPLICATION_ENV): ?>
<h3>Exception information:</h3>
<p><b>Exception Class:</b> <?php echo get_class($this->exception) ?></p>
<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p><hr />

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?></pre><hr />

<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
<?php endif ?>