<script src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<form id="acceptFrom" action="<?php echo APP_CTX?>/widget/response/refresh" method="post">
	Accept Screen
</form>
<script type="text/javascript">
var timerRefresh = window.setInterval(refreshPage, 5000);

function refreshPage() {
	$("#acceptFrom").ajaxSubmit(function(result) {
		if (result.redirect == true) {
			window.location.replace(result.url);
		}
	});
}
</script>