<?php $country = $_SESSION["country"]?>
<form id="responseFrom" action="<?php echo APP_CTX?>/widget/response/validate" method="post" onsubmit="submiteAnonCall('#responseFrom'); return false;">
	<p><span class="AVC_tagline"><?php echo MultiLang::getText("Response_1", $country, $this->name)?></span></p>
	<div class="_idGenObjectLayout-1">
		<div class="_idGenPageitem-4">
			<img class="_idGenPageitem-3" src="<?php echo APP_CTX?>/image/gmail_avatar.png" alt="" />
		</div>
	</div>
	
	<div style="display:<?php echo $this->inviteePay?>">
		<p><span class="h2"><?php echo MultiLang::getText("Response_2", $country, $this->freeCallDur)?></span></p>
		<p><span class="form"><?php echo MultiLang::getText3("Response_3", $country, $this->chargeAmount, $this->minCallBlkDur, $this->freeCallDur)?></span></p>
	</div>
	<div style="margin-top: 10px; margin-bottom: 20px; display:<?php echo $this->inviterPay?>">
		<p><span class="form"><?php echo MultiLang::getText("Response_4", $country, $this->name)?></span></p>
	</div>
	
	<p style="margin-top: 10px"><span class="h2"><?php echo MultiLang::getText("Response_5", $country)?></span></p>
	<p style="margin-top: 8px"><span class="form"><?php echo MultiLang::getText("Response_6", $country)?></span></p>
	<div class="_idGenObjectLayout-1">
		<div class="_idGenPageitem-8">
			<img class="_idGenPageitem-7" src="<?php echo APP_CTX?>/image/Lock.png" alt="" />
		</div>
		<input value="14158004768" type="text" name="inviteePhoneNumber" onkeypress="inputCheck('[0-9]', event)" tabindex="1" />
		<div class="_idGenPageitem-8">
			<img class="_idGenPageitem-7" src="<?php echo APP_CTX?>/image/Lock.png" alt="" />
		</div>
	</div>
	<p><span class="form"><?php echo MultiLang::getText("Response_7", $country)?></span></p>
	<p class="message">
		<small id="inviteePhoneNumberInvalid"><?php echo MultiLang::getText("Message_2", $country)?></small>
	</p>

	<div class="bottom">
		<input type="submit" id="agreeButton" value="<?php echo MultiLang::getText("Response_8", $country)?>" disabled /><br>
		<input type="checkbox" id="agreeCheckbox" tabindex="1" onclick="checkAgree('#agreeCheckbox', '#agreeButton')" />
		<span class="form"><?php echo MultiLang::getText("General_2", $country)?></span><br>
		<p><span class="form">
			<?php echo MultiLang::getText("Response_9", $country)?>
			<a href="<?php echo APP_CTX?>/widget/response/decline"><?php echo MultiLang::getText("Response_10", $country)?></a>
			<?php echo MultiLang::getText("Response_11", $country)?>
		</span></p>
	</div>
</form>
