<script type="text/javascript" src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<h1><?php echo MultiLang::getText("Make_a_Tokumei_call_to", $country, $this->inviterName)?></h1><br>
<form id="responseFrom" action="<?php echo APP_CTX?>/widget/response/validate" method="post" onsubmit="submiteAnonCall('#responseFrom'); return false;">
	<div id="inviteePay" style="display:<?php echo $this->inviteePay?>">
		<div>Free Call Dur: <?php echo $this->freeCallDur?></div>
		<div>Charge Amount: <?php echo $this->chargeAmount?></div>
		<div>Min Call Blk Dur: <?php echo $this->minCallBlkDur?></div>
	</div>
	<div id="inviterPay" style="display:<?php echo $this->inviterPay?>">
		Inviter pay
	</div>
	<div>
		<input value="14158004768" type="text" name="inviteePhoneNumber" onkeypress="inputCheck('[0-9]', event)" placeholder="<?php echo MultiLang::getText("Phone_number", $country)?>" tabindex="1" />
		<small id="inviteePhoneNumberInvalid" style="display:none">
			<?php echo MultiLang::getText("Phone_number", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
		</small>
	</div><br>
	<div>
		<input type="submit" value="Accept" />
	</div>
	<div>
		<input type="checkbox" name="agreement" tabindex="1" />I agree
		<small id="agreementInvalid" style="display:none">
			agreement invalid
		</small>
	</div>
	<div>
		<a href="<?php echo APP_CTX?>/widget/response/decline"></a>
	</div>
</form>
<form id="refreshFrom" action="<?php echo APP_CTX?>/widget/response/refresh" method="post">
	Accept Screen
</form>
<script type="text/javascript">
var timerRefresh = window.setInterval(refreshPage, 5000);

function refreshPage() {
	$("#refreshFrom").ajaxSubmit(function(result) {
		if (result.redirect == true) {
			window.location.replace(result.url);
		}
	});
}
</script>
