<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="Content-style-Type" content="text/html; charset=UTF-8">
    <title>ジモティー電話相談サービス</title>
    <link href="<?php echo APP_CTX ?>/pc/css/style.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="<?php echo APP_CTX ?>/components/library/jquery/jquery.min.js"></script>
    <script type="text/javascript"
            src="<?php echo APP_CTX ?>/components/library/jquery/jquery.validate.min.js"></script>
    <script type="text/javascript" src="<?php echo APP_CTX ?>/components/library/jquery/messages_ja.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-61531837-1', 'auto');
        ga('send', 'pageview');

        $.validator.addMethod("jpphone", function (value, element) {
            /* commentted by Huan for Feathre #118
             return this.optional(element) || /^\+(0){0,4}(81){1}[0-9]{9,11}$/.test(value) || /^[ ]*[\+]{0,1}(0){0,4}(1){1}[0-9]{10}[ ]*$/.test(value) || /^[ ]*[\+]{0,1}(0){0,4}(65){1}[0-9]{8}[ ]*$/.test(value);
             */

            return this.optional(element) || /^\+\d{3,18}$/.test(value) || /^\d{3,18}$/.test(value);

            //return true;
        }, "有効な電話番号を入力してください。");

        $().ready(function () {
            var validator = $('#pcsteponeForm').validate();

            $('#submitLink').click(function () {
                if (validator.form()) {
                    $('#pcsteponeForm').submit();
                } else {
                    return 0;
                }
            });
        });
    </script>
</head>
<body>
<div class="container">
    <div id="header"></div>
    <div class="container_inner" style="width:1000px; background-image:none !important;">
        <div class="clearfix c_both" id="logo">
            <div class="header_logo"><img alt="ジモティー" height="33" src="<?php echo APP_CTX ?>/pc/images/jmty_thin.png" style="float:left"
                                          width="120"> <br class="c_both">
            </div>
            <br class="c_both">
        </div>
        <div class="clearfix" id="breadcrumbs"> <span>
          <div> 必要項目入力</div>
          </span> <span> &nbsp;&gt;&nbsp; </span> <span> 入力内容確認 </span> <span> &nbsp;&gt;&nbsp; </span>
            <span> 登録完了 </span> <br class="c-both">
        </div>
        <div class="page_content">
            <form id="pcsteponeForm" action="<?php echo APP_CTX ?>/pc/validatecreditcard" method="post">
                <div class="text01">電話相談サービスご利用には、ご連絡先やお支払い情報の入力が必要です。<br>
                    登録完了しましたら通話を開始できます。
                </div>
                    <?php
                    if (!$this->formValue->validate) {
                        echo "<div class='text01'>クレジットカード情報が正しくありません。確認と再入力をお願いします。</div>";
                    }
                    ?>
                <div class="section">
                    <div class="section_title">
                        <div class="section_title_inner">
                            <h2><span class="p"> 必要項目入力 </span></h2>
                        </div>
                    </div>
                    <div class="section_content">
                        <table class="tabular table_two_line table_two_piece" summary="credit_1" id="credit">
                            <tbody>
                            <tr>
                                <th>電話番号</th>
                                <td><input name="phone" type="text" id="phone" value="<?php echo $this->formValue->phone ?>" class="code required jpphone"
                                           maxlength="16" style="width:200px;"/><br><span>※こちらの番号宛に着信されます</span></td>
                            </tr>
                            <tr>
                                <th>メールアドレス</th>
                                <td><input name="email" type="text" id="email" value="<?php echo $this->formValue->email ?>" class="code required email"
                                           maxlength="255" style="width:300px;"/></td>
                            </tr>
                            <tr>
                                <th>カード種類</th>
                                <td><select name="CardType" class="required">
                                        <option value="01" <?php if ($this->formValue->CardType=="01") {echo "selected='selected'";} ?>>master</option>
                                        <option value="02" <?php if ($this->formValue->CardType=="02") {echo "selected='selected'";} ?>>visa</option>
                                        <option value="03" <?php if ($this->formValue->CardType=="03") {echo "selected='selected'";} ?>>amex</option>
                                    </select></td>
                            </tr>
                            <tr>
                                <th>カード名義人<br/>（半角ローマ字）</th>
                                <td> 名
                                    <input name="fname" type="text" id="fname" value="<?php echo $this->formValue->fname ?>" class="code required"
                                           maxlength="16" style="width:140px;"/>
                                    　姓
                                    <input name="lname" type="text" id="lname" value="<?php echo $this->formValue->lname ?>" class="code required"
                                           maxlength="16" style="width:140px;"/></td>
                            </tr>
                            <tr>
                                <th>カード番号<br>
                                </th>
                                <td><input name="CardNo" type="text" id="Name" value="<?php echo $this->formValue->CardNo ?>" class="code required number"
                                           maxlength="16" style="width:300px;"/><br/>
                                    <span>※ハイフン無し。数字のみ</span></td>
                            </tr>
                            <tr>
                                <th>カード有効期限</th>
                                <td><select name="ExpireMonth" class="required">
                                        <option value="01" <?php if ($this->formValue->ExpireMonth=="01") {echo "selected='selected'";} ?>>01</option>
                                        <option value="02" <?php if ($this->formValue->ExpireMonth=="02") {echo "selected='selected'";} ?>>02</option>
                                        <option value="03" <?php if ($this->formValue->ExpireMonth=="03") {echo "selected='selected'";} ?>>03</option>
                                        <option value="04" <?php if ($this->formValue->ExpireMonth=="04") {echo "selected='selected'";} ?>>04</option>
                                        <option value="05" <?php if ($this->formValue->ExpireMonth=="05") {echo "selected='selected'";} ?>>05</option>
                                        <option value="06" <?php if ($this->formValue->ExpireMonth=="06") {echo "selected='selected'";} ?>>06</option>
                                        <option value="07" <?php if ($this->formValue->ExpireMonth=="07") {echo "selected='selected'";} ?>>07</option>
                                        <option value="08" <?php if ($this->formValue->ExpireMonth=="08") {echo "selected='selected'";} ?>>08</option>
                                        <option value="09" <?php if ($this->formValue->ExpireMonth=="09") {echo "selected='selected'";} ?>>09</option>
                                        <option value="10" <?php if ($this->formValue->ExpireMonth=="10") {echo "selected='selected'";} ?>>10</option>
                                        <option value="11" <?php if ($this->formValue->ExpireMonth=="11") {echo "selected='selected'";} ?>>11</option>
                                        <option value="12" <?php if ($this->formValue->ExpireMonth=="12") {echo "selected='selected'";} ?>>12</option>
                                    </select>
                                    月
                                    <select name="ExpireYear" class="required">
                                        <option value="2015" <?php if ($this->formValue->ExpireYear=="2015") {echo "selected='selected'";} ?>>2015</option>
                                        <option value="2016" <?php if ($this->formValue->ExpireYear=="2016") {echo "selected='selected'";} ?>>2016</option>
                                        <option value="2017" <?php if ($this->formValue->ExpireYear=="2017") {echo "selected='selected'";} ?>>2017</option>
                                        <option value="2018" <?php if ($this->formValue->ExpireYear=="2018") {echo "selected='selected'";} ?>>2018</option>
                                        <option value="2019" <?php if ($this->formValue->ExpireYear=="2019") {echo "selected='selected'";} ?>>2019</option>
                                        <option value="2020" <?php if ($this->formValue->ExpireYear=="2020") {echo "selected='selected'";} ?>>2020</option>
                                        <option value="2021" <?php if ($this->formValue->ExpireYear=="2021") {echo "selected='selected'";} ?>>2021</option>
                                        <option value="2022" <?php if ($this->formValue->ExpireYear=="2022") {echo "selected='selected'";} ?>>2022</option>
                                        <option value="2023" <?php if ($this->formValue->ExpireYear=="2023") {echo "selected='selected'";} ?>>2023</option>
                                        <option value="2024" <?php if ($this->formValue->ExpireYear=="2024") {echo "selected='selected'";} ?>>2024</option>
                                        <option value="2025" <?php if ($this->formValue->ExpireYear=="2025") {echo "selected='selected'";} ?>>2025</option>
                                        <option value="2026" <?php if ($this->formValue->ExpireYear=="2026") {echo "selected='selected'";} ?>>2026</option>
                                        <option value="2027" <?php if ($this->formValue->ExpireYear=="2027") {echo "selected='selected'";} ?>>2027</option>
                                        <option value="2028" <?php if ($this->formValue->ExpireYear=="2028") {echo "selected='selected'";} ?>>2028</option>
                                        <option value="2029" <?php if ($this->formValue->ExpireYear=="2029") {echo "selected='selected'";} ?>>2029</option>
                                        <option value="2030" <?php if ($this->formValue->ExpireYear=="2030") {echo "selected='selected'";} ?>>2030</option>
                                        <option value="2031" <?php if ($this->formValue->ExpireYear=="2031") {echo "selected='selected'";} ?>>2031</option>
                                        <option value="2032" <?php if ($this->formValue->ExpireYear=="2032") {echo "selected='selected'";} ?>>2032</option>
                                        <option value="2033" <?php if ($this->formValue->ExpireYear=="2033") {echo "selected='selected'";} ?>>2033</option>
                                        <option value="2034" <?php if ($this->formValue->ExpireYear=="2034") {echo "selected='selected'";} ?>>2034</option>
                                    </select>
                                    年
                                </td>
                            </tr>
                            <tr>
                                <th>セキュリティコード</th>
                                <td><input name="cvv" type="text" id="cvv" value="<?php echo $this->formValue->cvv ?>" class="code required number"
                                           minlength="3" maxlength="4" size="6"></td>
                            </tr>
                            </tbody>
                        </table>

                        <!-- MemberCardArray -->

                        <div class="btn"><a href="#" id="submitLink" style="cursor:hand">
                                <div>入力内容を確認</div>
                            </a></div>

                    </div>
                </div>
            </form>
            <br class="clear">
        </div>
    </div>
    <div id="footer">
        <div class="copyright"> COPYRIGHT (C) 2011 - 2015 Jimoty, Inc. ALL RIGHTS RESERVED.</div>
    </div>
    ・
</div>
</body>
</html>