
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-style-Type" content="text/html; charset=utf-8">
	<title>ジモティー電話相談サービス</title>
	<link href="css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
    <div class="container">
      <div id="header"> </div>
      <div class="container_inner" style="width:1000px; background-image:none !important;">
        <div class="clearfix c_both" id="logo">
          <div class="header_logo"> <img alt="ジモティー" height="33" src="images/jmty_thin.png" style="float:left" width="120"> <br class="c_both">
          </div>
          <br class="c_both">
        </div>
        <div class="clearfix" id="breadcrumbs"> <span>
          <div> 必要項目入力 </div>
          </span> <span> &nbsp;&gt;&nbsp; </span> <span> 入力内容確認 </span> <span> &nbsp;&gt;&nbsp; </span> <span> 登録完了 </span> <br class="c-both">
        </div>
        <div class="page_content">
                          <div class="text01">電話相談サービスご利用には、ご連絡先やお支払い情報の入力が必要です。<br>
                登録完了しましたら通話を開始できます。</div>
            <div class="section">
              <div class="section_title">
                <div class="section_title_inner">
                  <h2> <span class="p"> 必要項目入力 </span> </h2>
                </div>
              </div>
              <div class="section_content">
                <table class="tabular table_two_line table_two_piece" summary="credit_1" id="credit">
                  <tbody>
                    <tr>
                      <th>電話番号</th>
                      <td><input name="phone" type="text" id="phone" value="" class="code" maxlength="16" style="width:200px;"/><br><span>※こちらの番号宛に着信されます</span></td>
                    </tr>
                    <tr>
                      <th>メールアドレス</th>
                      <td><input name="email" type="text" id="email" value="" class="code" maxlength="255" style="width:300px;"/></td>
                    </tr>
                    <tr>
                      <th>カード種類</th>
                      <td><select name="CardType">
                          <option value="01">master</option>
                          <option value="02">visa</option>
                          <option value="03">カード会社</option>
                        </select></td>
                    </tr>
                    <tr>
                      <th>カード名義人<br/>（半角ローマ字）</th>
                      <td> 名
                        <input name="fname" type="text" id="fname" value="" class="code" maxlength="16" style="width:140px;"/>
                        　姓
                        <input name="lname" type="text" id="lname" value="" class="code" maxlength="16"  style="width:140px;"/></td>
                    </tr>
                    <tr>
                      <th>カード番号<br>
                      </th>
                      <td><input name="CardNo" type="text" id="Name" value="" class="code" maxlength="16" style="width:300px;"/><br/>
                        <span>※ハイフン無し。数字のみ</span></td>
                    </tr>
                    <tr>
                      <th>カード有効期限</th>
                      <td><select name="ExpireMonth">
                          <option value="01">01</option>
                          <option value="02">02</option>
                          <option value="03">03</option>
                          <option value="04">04</option>
                          <option value="05">05</option>
                          <option value="06">06</option>
                          <option value="07">07</option>
                          <option value="08">08</option>
                          <option value="09">09</option>
                          <option value="10">10</option>
                          <option value="11">11</option>
                          <option value="12">12</option>
                        </select>
                        月
                        <select name="ExpireYear">
                          <option value="15">15</option>
                          <option value="16">16</option>
                          <option value="17">17</option>
                          <option value="18">18</option>
                          <option value="19">19</option>
                          <option value="20">20</option>
                          <option value="21">21</option>
                          <option value="22">22</option>
                          <option value="23">23</option>
                          <option value="24">24</option>
                          <option value="25">25</option>
                          <option value="26">26</option>
                          <option value="27">27</option>
                          <option value="28">28</option>
                          <option value="29">29</option>
                          <option value="30">30</option>
                          <option value="31">31</option>
                          <option value="32">32</option>
                          <option value="33">33</option>
                          <option value="34">34</option>
                        </select>
                        年 </td>
                    </tr>
                    <tr>
                      <th>セキュリティコード</th>
                      <td><input name="cvv" type="text" id="cvv" value="" class="code" maxlength="4" size="6"></td>
                    </tr>
                  </tbody>
                </table>

                <!-- MemberCardArray -->

                <div class="btn"> <a href="pc_credit_2.html">
                  <div>入力内容を確認</div>
                  </a> </div>
              </div>
            </div>
            <br class="clear">
        </div>
      </div>
      <div id="footer">
        <div class="copyright"> COPYRIGHT (C) 2011 - 2015 Jimoty, Inc. ALL RIGHTS RESERVED. </div>
      </div>
      ・ </div>
</body>
</html>