<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=Shift_JIS">
  <meta http-equiv="Content-style-Type" content="text/html; charset=Shift_JIS">
  <title>ジモティー電話相談サービス</title>
  <link href="css/style.css" rel="stylesheet" type="text/css">
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-61531837-1', 'auto');
        ga('send', 'pageview');
    </script>
</head>
<body>
<div class="container">
  <div id="header"></div>
  <div class="container_inner" style="width:1000px; background-image:none !important;">
    <div class="clearfix c_both" id="logo">
      <div class="header_logo"><img alt="ジモティー" height="33" src="images/jmty_thin.png" style="float:left" width="120">
        <br class="c_both">
      </div>
      <br class="c_both">
    </div>
    <div class="clearfix" id="breadcrumbs">
        <span>
         <span>必要項目入力</span> 
          </span> <span> &nbsp;&gt;&nbsp; </span><span>入力内容確認</span><span> &nbsp;&gt;&nbsp; </span>

      <div>登録完了</div>
      <br class="c-both">
    </div>
    <div class="page_content">
      <div class="section">
        <div class="section_title">
          <div class="section_title_inner">
            <h2><span class="p">登録完了</span></h2>
          </div>
        </div>
        <div class="section_content">
          <p class="done">登録が完了しました</p>

          <div>下記のボタンをタップすると、ご登録の番号にこちらより着信が入ります。<br>そのままメンターへお電話がつながりますのでそのままお話ください。
          </div>
          <div class="btn">
            <a href="#">
              <div>すぐに通話を開始</div>
            </a></div>
          </div>
        </div>
        <br class="clear">

      </div>
    </div>
    <div id="footer">
      <div class="copyright"> COPYRIGHT (C) 2011 - 2015 Jimoty, Inc. ALL RIGHTS RESERVED.</div>
    </div>
    ・
  </div>
</body>
</html>