
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-style-Type" content="text/html; charset=utf-8">
	<title>ジモティー電話相談サービス</title>
	<link href="css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
    <div class="container">
      <div id="header"> </div>
      <div class="container_inner" style="width:1000px; background-image:none !important;">
        <div class="clearfix c_both" id="logo">
          <div class="header_logo"> <img alt="ジモティー" height="33" src="images/jmty_thin.png" style="float:left" width="120"> <br class="c_both">
          </div>
          <br class="c_both">
        </div>
        <div class="clearfix" id="breadcrumbs"> <span>
         <span>必要項目入力</span> 
          </span> <span> &nbsp;&gt;&nbsp; </span><div> 入力内容確認 </div><span> &nbsp;&gt;&nbsp; </span> <span> 登録完了 </span> <br class="c-both">
        </div>
        <div class="page_content">
            <p>
            </p>
            <div class="section">
              <div class="section_title">
                <div class="section_title_inner">
                  <h2> <span class="p">入力内容確認</span> </h2>
                </div>
              </div>
              <div class="section_content">
                <table class="tabular table_two_line table_two_piece" summary="credit_1" id="credit">
                  <tbody>
                    <tr>
                      <th>電話番号</th>
                      <td>090-0000-1111</td>
                    </tr>
                    <tr>
                      <th>メールアドレス</th>
                      <td>soudan_hanako@jmty.jp</td>
                    </tr>
                    <tr>
                      <th>カード会社</th>
                      <td>VISA</td>
                    </tr>
                    <tr>
                      <th>カード名義人<br>
                      </th>
                      <td>HANAKO SOUDAN</td>
                    </tr>
                    <tr>
                      <th>カード番号<br>
                      </th>
                      <td>1111************</td>
                    </tr>
                    <tr>
                      <th>カード有効期限</th>
                      <td>
                        01月01年 </td>
                    </tr>
                    <tr>
                      <th>セキュリティコード</th>
                      <td>****</td>
                    </tr>
                  </tbody>
                </table>
                
                <div class="section_content">
                <div>必ず本利用規約をご一読の上、内容をご確認いただいた上でご登録ください。<br>
                <input type="checkbox" name="#" value="#" ><a href="">利用規約</a>に同意する</div>
                <div class="btn">
                 <a href="pc_credit_3.html">
                  <div>入力内容を登録</div>
                  </a> </div>
              </div>
                  
              </div>
            </div>
            <br class="clear">
        </div>
      </div>
      <div id="footer">
        <div class="copyright"> COPYRIGHT (C) 2011 - 2015 Jimoty, Inc. ALL RIGHTS RESERVED. </div>
      </div>
      ・ </div>
</body>
</html>