<!DOCTYPE html>
<html lang="ja">
<head>
  <script type="text/javascript">Object.defineProperty(window.navigator, 'userAgent', {
    get: function () {
      return 'Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5';
    }
  });
  Object.defineProperty(window.navigator, 'vendor', {
    get: function () {
      return 'Apple, Inc.';
    }
  });
  Object.defineProperty(window.navigator, 'platform', {
    get: function () {
      return 'iPhone';
    }
  });</script>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="UTF-8">
  <meta content="index,follow" name="robots">
  <title>ジモティー 中古・フリマ・フリーマーケット、バイト、スクール、募集の無料広告の掲示板</title>
  <meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0"
        name="viewport">
  <meta content="telephone=no" name="format-detection">
  <link href="<?php echo APP_CTX; ?>/sp/css/style.css" media="screen" rel="stylesheet" type="text/css">


<body>
<div id="container">
  <div id="main">
    <div id="header">
      <div class="hdbox">
        <h1 id="page_head_text"><span class="font_size13"> ジモティー電話相談サービス - 登録完了</span></h1>
      </div>
      <div id="header_action">
        <div class="header_logo"><a href="https://jmty.jp/s">
          <img alt="" height="40" src="images/header_logo.png" width="80"> </a></div>
        <br class="c-both">
      </div>
    </div>
    <div id="page_flat_title">
      <h2>登録完了</h2>
    </div>
    <div class="margin_top_5" id="breadcrumb_list">必要項目の入力&nbsp;&gt;&nbsp;入力内容確認&nbsp;&gt;&nbsp;<span>登録完了</span></div>

    <div class="post_form">

      <div class="line text_aline_center">
        <div class="line fontbold">ご利用ありがとうございます。</div>
      </div>

      <div class="line text_aline_left">
        ご登録の電話番号に発信を行いました。<br>そのまま相談員へお電話が繋がりますので、そのままお話しください。
      </div>

    </div>
    <div id="footer">
      <div id="footer_padding">
        <br class="c-both">
      </div>
      <div style="text-align:center;font-size:9px;">

        COPYRIGHT(C)2011-2015 Jimoty, Inc. ALL RIGHTS RESERVED.

      </div>
    </div>
  </div>
</div>
</body>
</html>