<link rel="stylesheet" href="<?php echo APP_CTX?>/css/jquery-ui-1.10.4.custom.min.css" />
<script type="text/javascript" src="<?php echo APP_CTX?>/script/jquery-ui-1.10.4.custom.min.js"></script>
<?php $country = $this->country?>
<form id="reportFrom" action="<?php echo APP_CTX?>/widget/report/validate" method="post" onsubmit="submiteAnonCall('#reportFrom'); return false;">
	<h3><?php echo MultiLang::getText("Start_date", $country)?></h3>
	<div>
		<input type="text" id="startDate" name="startDate" value="<?php $this->startDate?>" tabindex="1" />
	</div><br>
	<h3><?php echo MultiLang::getText("End_date", $country)?></h3>
	<div>
		<input type="text" id="endDate" name="endDate" value="<?php $this->endDate?>" tabindex="1" />
	</div><br>
</form>
<script type="text/javascript">
$(function() {
	$("#startDate").datepicker({
		dateFormat:  'mm/dd/yy',
		yearRange:   "2014:",
		changeYear:  true,
		changeMonth: true,
		showWeek:    true,
		onSelect:function(dateText,inst) {
			$("#endDate").datepicker("option", "minDate", new Date(dateText));
		}
	});
	$("#endDate").datepicker({
		dateFormat:  'mm/dd/yy',
		yearRange:   "2014:",
		changeYear:  true,
		changeMonth: true,
		showWeek:    true,
			onSelect:function(dateText,inst) {
			$("#startDate").datepicker("option", "maxDate", new Date(dateText));
		}
	});
});
</script>