<html>
<head>
<script src="<?php echo APP_CTX?>/script/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
function showAnonCall() {
	$("#popScreen").css("display", "block");
	$("#togleDisp").slideDown();
}
function removeAnonCall() {
	$('#popScreen').fadeOut();
	setTimeout("$('#togleDisp').css('display', 'none')", 1000);
}
</script>
<link rel="stylesheet" type="text/css" href="<?php echo APP_CTX?>/css/landing.css" />
</head>
<body>
	<div id="bigButton" onclick="javascript:showAnonCall()"></div>
	<div id="popScreen">
		<div id="baseFrame">
			<div id="midCentFrame">
				<div id="togleDisp" style="display: none">
					<div id="closeFrame" class="inlineFrame"></div>
					<div class="inlineFrame">
						<div id="mainFrame">
							<iframe id="realFrame" src="<?php echo $this->src?>"></iframe>
						</div>
					</div>
					<div id="closeFrame" class="inlineFrame">
						<a id=closeImg href="javascript:removeAnonCall();"></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>