<html>
<head>
<link rel="stylesheet" type="text/css" href="<?php echo APP_CTX?>/css/landing.css" />
<script src="<?php echo APP_CTX?>/script/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
function showAnonCall() {
	$("#popScreen").css("display", "none");
}
</script>
</head>
<body onload="showAnonCall()">
	<div class="bg-img"></div>
	<div class="bg-hue"></div>
	<div id="popScreen">
		<div id="baseFrame">
			<div id="midCentFrame">
				<div id="mainFrame">
					<iframe id="realFrame" src="<?php echo $this->src?>"></iframe>
				</div>
			</div>
		</div>
	</div>
</body>
</html>