<?php $country = $_SESSION["country"]?>
<div id="header">
	<div class="_idGenObjectLayout-1">
		<div class="_idGenPageitem-2">
			<img class="_idGenPageitem-1" src="<?php echo APP_CTX?>/image/logo-ns-131205.png" alt="" />
		</div>
	</div>
	<div class="Basic-Text-Frame">
		<p><span class="CharOverride-1"><?php echo MultiLang::getText("General_1", $country)?></span></p>
	</div>
	<div class="redline"></div>
</div>
