<?php $country = $this->country?>
<form id="acceptFrom" action="<?php echo APP_CTX?>/widget/notification/refresh-response" method="post">
	<p style="margin-top: 80px"><span class="notification_text"><?php echo MultiLang::getText("ResponseAccept_1", $country, $this->name)?></span></p>
</form>
<script type="text/javascript">
var timerRefresh = window.setInterval(refreshPage, 5000);

function refreshPage() {
	$("#acceptFrom").ajaxSubmit(function(result) {
		if (result.redirect == true) {
			window.location.replace(result.url);
		}
	});
}
</script>