<script type="text/javascript" src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<h1><?php echo MultiLang::getText("Make_a_Tokumei_call_to", $country, $this->inviterName)?></h1><br>
<form id="responseFrom" action="<?php echo APP_CTX?>/widget/response/validate" method="post" onsubmit="submiteAnonCall('#responseFrom'); return false;">
	<div id="ccInfo" style="display:<?php echo $this->ccInfo?>">
		<input type="text" name="creditCardNumber" onkeypress="inputCheck('[0-9]|\-', event)" placeholder="<?php echo MultiLang::getText("Credit_Card_Number", $country)?>" tabindex="1" /><br>
		<input type="twothird" name="creditCardExp" onkeypress="inputCheck('[0-9]|\/', event)" placeholder="<?php echo MultiLang::getText("Exp", $country)?>" tabindex="1" />
		<input type="fourth" name="creditCardCvc" onkeypress="inputCheck('[0-9]', event)" placeholder="<?php echo MultiLang::getText("CVC", $country)?>" tabindex="1" />
		<small id="creditCardInfoInvalid" style="display:none">
			<?php echo MultiLang::getText("Credit_Card_Information", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
		</small>
	</div><br>
	<h3><?php echo MultiLang::getText("Enter_your_phone_number", $country)?></h3>
	<h4><?php echo MultiLang::getText("This_number_will_be_kept_private", $country)?></h4>
	<div>
		<input value="14158004768" type="text" name="inviteePhoneNumber" onkeypress="inputCheck('[0-9]', event)" placeholder="<?php echo MultiLang::getText("Phone_number", $country)?>" tabindex="1" />
		<small id="inviteePhoneNumberInvalid" style="display:none">
			<?php echo MultiLang::getText("Phone_number", $country)?><?php echo MultiLang::getText("is_invalid", $country)?>
		</small>
	</div><br>
	<div>
		<input type="submit" value="<?php echo MultiLang::getText("Make_the_call", $country)?>" />
	</div>
	<input type="hidden" name="hasCcInfo" value="<?php echo $this->hasCcInfo?>" />
	<input type="hidden" name="inviteInx" value="<?php echo $this->inviteInx?>" />
	<input type="hidden" name="partnerInx" value="<?php echo $this->partnerInx?>" />
	<input type="hidden" name="inviterInx" value="<?php echo $this->inviterInx?>" />
	<input type="hidden" name="inviteeInx" value="<?php echo $this->inviteeInx?>" />
</form>

