<?php $country = $_SESSION["country"]?>
<form id="responseFrom" action="<?php echo APP_CTX?>/widget/response/validate" method="post" onsubmit="submiteAnonCall('#responseFrom', '#agreeCheckbox', '#agreeInvalid'); return false;">
	<div class="topShort">
		<p style="margin-top: 28px"><span class="AVC_tagline"><?php echo MultiLang::getText("Response_1", $country, $this->name)?></span></p>
		
		<div style="margin-top: 30px; display:<?php echo $this->inviteePay?>">
			<p><span class="h2"><?php echo MultiLang::getText("Response_2", $country, $this->freeCallDur)?></span></p>
			<p><span class="form"><?php echo MultiLang::getText3("Response_3", $country, $this->chargeAmount, $this->minCallBlkDur, $this->freeCallDur)?></span></p>
		</div>
		<div style="margin-top: 30px; margin-bottom: 20px; display:<?php echo $this->inviterPay?>">
			<p><span class="form"><?php echo MultiLang::getText("Response_4", $country, $this->name)?></span></p>
		</div>
		
		<p style="margin-top: 40px"><span class="h2"><?php echo MultiLang::getText("Response_5", $country)?></span></p>
		<p style="margin-top: 8px"><span class="form"><?php echo MultiLang::getText("Response_6", $country)?></span></p>
		<div class="_idGenObjectLayout-1">
			<div class="_idGenPageitem-8">
				<img class="_idGenPageitem-7" src="<?php echo APP_CTX?>/images/Lock.png" alt="" />
			</div>
			<input type="text" name="inviteePhoneNumber" class="phoneNumber" onkeypress="inputCheck('[0-9-]', event)" placeholder="<?php echo MultiLang::getText("General_6", $country)?>" tabindex="1" />
			<div class="_idGenPageitem-8">
				<img class="_idGenPageitem-7" src="<?php echo APP_CTX?>/images/Lock.png" alt="" />
			</div>
		</div>
		<p><span class="form"><?php echo MultiLang::getText("Response_7", $country)?></span></p>
		<p class="message">
			<span id="inviteePhoneNumberInvalid"><?php echo MultiLang::getText("Message_2", $country)?></span>
		</p>
	</div>

	<p class="message">
		<span id="agreeInvalid"><?php echo MultiLang::getText("Message_11", $country)?></span>
	</p>
	<input type="checkbox" id="agreeCheckbox" tabindex="1" />
	<label for="agreeCheckbox"><span class="form"><?php echo MultiLang::getText("General_2", $country)?></span></label><br>
	<input type="submit" id="agreeButton" value="<?php echo MultiLang::getText("Response_8", $country)?>" /><br>
	<p><span class="form">
		<?php echo MultiLang::getText("Response_9", $country)?>
		<a href="<?php echo APP_CTX?>/widget/response/decline"><?php echo MultiLang::getText("Response_10", $country)?></a>
		<?php echo MultiLang::getText("Response_11", $country)?>
	</span></p>
</form>
