<?php $country = $_SESSION["country"]?>
<p style="margin-top: 20px"><span class="notification_text"><?php echo MultiLang::getText("Expired_1", $country)?></span></p>
<p style="margin-top: 30px"><span class="notification_text"><?php echo MultiLang::getText("Expired_2", $country)?></span></p>
<div class="low">
	<form id="expiredFrom" action="<?php echo APP_CTX?>/widget/invitation/getstart" method="post">
		<input type="submit" value="<?php echo MultiLang::getText("Expired_3", $country)?>" />
	</form>
</div>
