<?php $country = $_SESSION["country"]?>
<p style="margin-top: 60px"><span class="notification_text"><?php echo MultiLang::getText("Ready_1", $country)?></span></p>
<p style="margin-top: 40px"><span class="notification_text"><?php echo MultiLang::getText("Ready_2", $country, $this->name)?></span></p>

<p style="margin-top: 30px">
	<span class="oneThird red"><?php echo $this->woman?></span>
	<span class="middle red"></span>
	<span class="oneThird red"><?php echo $this->man?></span>
</p>
<div style="margin-top: 10px" class="_idGenObjectLayout-1 low">
	<div class="_idGenPageitem-6"><p><span class="caption_cloud_small"></span></p></div>
</div>
