<?php $country = $_SESSION["country"]?>
<p style="margin-top: 60px"><span class="notification_text"><?php echo MultiLang::getText("Ready_1", $country)?></span></p>
<p style="margin-top: 40px"><span class="notification_text"><?php echo MultiLang::getText("Ready_2", $country, $this->name)?></span></p>
<div style="margin-top: 40px" class="_idGenObjectLayout-1 low">
	<div class="_idGenPageitem-4">
		<img class="_idGenPageitem-3" src="<?php echo APP_CTX?>/image/gmail_avatar.png" alt="" />
	</div>
	<div class="_idGenPageitem-6">
		<p><span class="caption_cloud_small"><?php echo MultiLang::getText("Ready_3", $country)?></span></p>
	</div>
	<div class="_idGenPageitem-4">
		<img class="_idGenPageitem-3" src="<?php echo APP_CTX?>/image/gmail_avatar.png" alt="" />
	</div>
</div>
