<?php $country = $_SESSION["country"]?>
<p style="margin-top: 20px"><span class="notification_text"><?php echo MultiLang::getText("Wrong_1", $country)?></span></p>
<p style="margin-top: 30px"><span class="notification_text"><?php echo MultiLang::getText("Wrong_2", $country)?></span></p>
<p style="margin-top: 30px"><span class="notification_text"><?php echo MultiLang::getText("Wrong_3", $country)?></span></p>
