<?php $country = $_SESSION["country"]?>
<p style="margin-top: 20px"><span class="notification_text"><?php echo MultiLang::getText("Wrong_1", $country)?></span></p>
<p style="margin-top: 30px"><span class="notification_text"><?php echo MultiLang::getText("Wrong_2", $country)?></span></p>
<p style="margin-top: 30px"><span class="notification_text"><?php echo MultiLang::getText("Wrong_3", $country)?></span></p>

<div style="margin-top: 20px" class="_idGenObjectLayout-1">
	<div class="_idGenPageitem-4">
		<img class="_idGenPageitem-3" src="<?php echo APP_CTX?>/images/Phones_M2.png" alt="" />
	</div>
</div>
