<?php $country = $_SESSION["country"]?>
	<p style="margin-top: 30px; margin-bottom: 40px"><span class="h2"><?php echo MultiLang::getText("Acceptance_1", $country)?></span></p>
	<p><span class="h2"><?php echo MultiLang::getText2("Acceptance_2", $country, $this->name, $this->freeCallDur)?></span></p>
	<p style="margin-top: 8px"><span class="form"><?php echo MultiLang::getText3("Acceptance_3", $country, $this->chargeAmount, $this->minCallBlkDur, $this->freeCallDur)?></span></p>
<div class="bottom">
	<form id="acceptanceFrom" action="<?php echo APP_CTX?>/widget/invitation/confirmation" method="post">
		<input type="submit" id="agreeButton" value="<?php echo MultiLang::getText("Acceptance_4", $country)?>" disabled /><br>
		<input type="checkbox" id="agreeCheckbox" tabindex="1" onclick="checkAgree('#agreeCheckbox', '#agreeButton')" />
		<span class="form"><?php echo MultiLang::getText("General_2", $country)?></span>
	</form>
</div>
