<?php $country = $_SESSION["country"]?>
<form id="acceptanceFrom" action="<?php echo APP_CTX?>/widget/invitation/confirmation" method="post">
	<p style="margin-top: 20px; margin-bottom: 30px"><span class="h2"><?php echo MultiLang::getText("Agreement_1", $country)?></span></p>
	<div style="display:<?php echo $this->inviterPay?>">
		<p><span class="h2"><?php echo MultiLang::getText2("Agreement_2", $country, $this->name, $this->freeCallDur)?></span></p>
		<p style="margin-top: 8px"><span class="form"><?php echo MultiLang::getText3("Agreement_3", $country, $this->chargeAmount, $this->minCallBlkDur, $this->freeCallDur)?></span></p>
	</div>
	<div style="margin-top: 10px; margin-bottom: 20px; display:<?php echo $this->inviteePay?>">
		<p><span class="h2"><?php echo MultiLang::getText2("Agreement_4", $country, $this->name, $this->freeCallDur)?></span></p>
	</div>

	<p style="margin-top: 20px"><span class="h2"><?php echo MultiLang::getText("Agreement_5", $country)?></span></p>
	<p style="margin-top: 6px"><span class="form"><?php echo MultiLang::getText("Agreement_6", $country)?></span></p>
	<input type="text" name="inviterProfile" tabindex="1" />
	
	<div class="bottom">
		<input style="width: 140px" type="submit" id="agreeButton" value="<?php echo MultiLang::getText("Agreement_7", $country)?>" disabled /><br>
		<input type="checkbox" id="agreeCheckbox" tabindex="1" onclick="checkAgree('#agreeCheckbox', '#agreeButton')" />
		<label for="agreeCheckbox"><span class="form"><?php echo MultiLang::getText("General_2", $country)?></span></label>
	</div>
</form>