<script src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<form id="confirmationFrom" action="<?php echo APP_CTX?>/widget/notification/refresh-invitation" method="post">
	Invitation sent to <?php echo $this->name?>
</form>
<script type="text/javascript">
var timerRefresh = window.setInterval(refreshPage, 5000);

function refreshPage() {
	$("#confirmationFrom").ajaxSubmit(function(result) {
		if (result.redirect == true) {
			window.location.replace(result.url);
		}
	});
}
</script>