<?php $country = $_SESSION["country"]?>
<form action="<?php echo APP_CTX?>/widget/invitation/invitation" method="post">
	<p style="margin-top: 20px"><span class="h1"><?php echo MultiLang::getText("GetStart_1", $country)?></span></p>
	<p><span class="form"><?php echo MultiLang::getText("GetStart_2", $country)?></span></p>
	
	<p style="margin-top: 30px"><span class="h1"><?php echo MultiLang::getText("GetStart_3", $country)?></span></p>
	<p><span class="form"><?php echo MultiLang::getText("GetStart_4", $country)?></span></p>
	<p><span class="form"><?php echo MultiLang::getText("GetStart_5", $country)?></span></p>
	<p><span class="form"><?php echo MultiLang::getText("GetStart_6", $country)?></span></p>
	
	<div style="margin-top: 20px" class="_idGenObjectLayout-1">
		<div class="_idGenPageitem-4">
			<img class="_idGenPageitem-3" src="<?php echo APP_CTX?>/image/gmail_avatar.png" alt="" />
		</div>
		<div class="_idGenPageitem-6">
			<p><span class="caption_cloud_small"><?php echo MultiLang::getText("GetStart_11", $country)?></span></p>
		</div>
		<div class="_idGenPageitem-4">
			<img class="_idGenPageitem-3" src="<?php echo APP_CTX?>/image/gmail_avatar.png" alt="" />
		</div>
	</div>
	
	<div class="bottom">
		<p><span class="h2"><?php echo MultiLang::getText("GetStart_7", $country)?></span></p>
		<p style="margin-top: 4px">
			<span class="form half"><?php echo MultiLang::getText("GetStart_8", $country)?></span>
			<span class="form half"><?php echo MultiLang::getText("GetStart_9", $country)?></span>
		</p>
		<input style="margin-top: 8px" class="half" type="submit" value="<?php echo MultiLang::getText("GetStart_10", $country)?>" onclick="setInviteType(1)" />
		<input class="half" type="submit" value="<?php echo MultiLang::getText("GetStart_10", $country)?>" onclick="setInviteType(2)" />
		<input type="hidden" id="inviteType" name="inviteType" />
	</div>
</form>
<script type="text/javascript">
function setInviteType(value) {
	$("#inviteType").val(value);
}
</script>