<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="keywords" content="insert keywords" />
<title>Version 1</title>
<link rel="stylesheet" href="<?php echo APP_CTX ?>/css/stylePrtnrWidget.css" type="text/css" />
<link rel="stylesheet" href="<?php echo APP_CTX ?>/css/styles/fontsWidget.css" type="text/css" media="screen" />
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700,300italic,400italic,600italic,700italic,300,600,800,800italic" type="text/css" />
<script type="text/JavaScript" src="<?php echo APP_CTX ?>/script/utils.js"></script>
</head>
<body>
	<div class="content">
		<article>
			<h1>Invite Someone to a Tokumei Call</h1>
			<br>
			<form action="inviteThanks.php" method="post" class="label-top">
				<h3>Enter your name</h3>
				<div>
					<p>
						<input type="text" name="inviterName" id="inviterName" value="Name" tabindex="1" onclick="clearInput(this)" />
					</p>
				</div>
				<br>
				<h3>Enter your phone number</h3>
				<br>
				<h4>This number will be kept private</h4>
				<br>
				<div>
					<p>
						<input type="text" name="userNumber" id="userNumber" value="Phone number" tabindex="1" onclick="clearInput(this)" />
					</p>
				</div>
				<h3>Enter their email address</h3>
				<div>
					<p>
						<input type="text" name="inviteEmail" id="inviteEmail" value="Email address" tabindex="1" onclick="clearInput(this)" />
					</p>
				</div>
				<br>
				<div>
					<input type="submit" value="Send invitation" />
				</div>
			</form>
		</article>
	</div>
</body>
</html>
