<?php $country = $_SESSION["country"]?>
<form id="invitationFrom" action="<?php echo APP_CTX?>/widget/invitation/validate" method="post" onsubmit="submiteAnonCall('#invitationFrom'); return false;">
	<div class="topLong">
		<p style="margin-bottom: 16px"><span class="h1"><?php echo MultiLang::getText("Invitation_1", $country)?></span></p>
		
		<p style="margin-bottom: 4px"><span class="h2 red"><?php echo MultiLang::getText("Invitation_2", $country)?></span></p>
		<p><span class="form"><?php echo MultiLang::getText("Invitation_3", $country)?></span></p>
		<input type="text" name="inviterEmail" tabindex="1" />
		<p class="message">
			<span id="inviterEmailInvalid"><?php echo MultiLang::getText("Message_1", $country)?></span>
		</p>
	
		<p style="margin-bottom: 4px"><span class="h2 red"><?php echo MultiLang::getText("Invitation_4", $country)?></span></p>
		<p><span class="form"><?php echo MultiLang::getText("Invitation_5", $country)?></span></p>
		<div class="_idGenObjectLayout-1">
			<div class="_idGenPageitem-8">
				<img class="_idGenPageitem-7" src="<?php echo APP_CTX?>/image/Lock.png" alt="" />
			</div>
			<input type="text" name="inviterPhoneNumber" class="phoneNumber" onkeypress="inputCheck('[0-9-]', event)" placeholder="<?php echo MultiLang::getText("General_6", $country)?>" tabindex="1" />
			<div class="_idGenPageitem-8">
				<img class="_idGenPageitem-7" src="<?php echo APP_CTX?>/image/Lock.png" alt="" />
			</div>
		</div>
		<p><span class="form"><?php echo MultiLang::getText("Invitation_6", $country)?></span></p>
		<p class="message">
			<span id="inviterPhoneNumberInvalid"><?php echo MultiLang::getText("Message_2", $country)?></span>
		</p>
			
		<p style="margin-bottom: 4px"><span class="h2 red"><?php echo MultiLang::getText("Invitation_7", $country)?></span></p>
		<p><span class="form"><?php echo MultiLang::getText("Invitation_8", $country)?></span></p>
		<p><span class="form"><?php echo MultiLang::getText("Invitation_9", $country)?></span></p>
		<input type="text" name="inviteeEmail" tabindex="1" />
		<p class="message">
			<span id="inviteeEmailInvalid"><?php echo MultiLang::getText("Message_1", $country)?></span>
		</p>
	</div>

	<input style="margin-top: 10px" type="submit" value="<?php echo MultiLang::getText("Invitation_10", $country)?>" />
</form>
