<?php $language = $this->language;?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="keywords" content="insert keywords" />
<title>Version 1</title>
<link rel="stylesheet" type="text/css" href="<?php echo APP_CTX?>/css/styleWidget.css" />
<link rel="stylesheet" type="text/css" href="<?php echo APP_CTX?>/css/fontsWidget.css" media="screen" />
</head>
<body>
	<div class="content">
		<article>
			<h1><?php echo MultiLang::getText("Invite_Someone_to_a_Tokumei_Call", $language)?></h1>
			<br>
			<form name="invitationFrom" action="<?php echo APP_CTX?>/widget/invitation/validate" method="post" class="label-top">
				<h3><?php echo MultiLang::getText("Enter_your_name", $language)?></h3>
				<div><p>
					<input type="text" name="inviterName" placeholder="<?php echo MultiLang::getText("Name", $language)?>" value="<?php echo $this->inviterName?>" tabindex="1" />
				</p></div><br>
				<h3><?php echo MultiLang::getText("Enter_your_phone_number", $language)?></h3>
				<h4><?php echo MultiLang::getText("This_number_will_be_kept_private", $language)?></h4>
				<div><p>
					<input type="text" name="inviterNumber" placeholder="<?php echo MultiLang::getText("Phone_number", $language)?>" value="<?php echo $this->inviterNumber?>" tabindex="1" />
					<small style="display:<?php echo $this->msgInviterNumberStyle?>">
						<?php echo MultiLang::getText("Phone_number", $language)?><?php echo MultiLang::getText("is_invalid", $language)?>
					</small>
				</p></div><br>
				<h3><?php echo MultiLang::getText("Enter_their_email_address", $language)?></h3>
				<div><p>
					<input type="text" name="inviteeEmail" placeholder="<?php echo MultiLang::getText("Email_address", $language)?>" value="<?php echo $this->inviteeEmail?>" tabindex="1" />
					<small style="display:<?php echo $this->msgInviterEmailStyle?>">
						<?php echo MultiLang::getText("Email_address", $language)?><?php echo MultiLang::getText("is_invalid", $language)?>
					</small>
				</p></div><br>
				<div>
					<input type="submit" value="<?php echo MultiLang::getText("Send_inviation", $language)?>" />
				</div>
				<input type="hidden" name="token" value="<?php echo $this->token?>" />
			</form>
		</article>
	</div>
</body>
</html>
