<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="keywords" content="insert keywords" />
<title><?php echo $this->title ? $this->title : APP_TITLE ?></title>
<script src="<?php echo APP_CTX?>/script/jquery-1.11.1.min.js"></script>
<script src="<?php echo APP_CTX?>/script/jquery.form.min.js"></script>
<script src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo APP_CTX?>/css/anoncall.css" />
</head>
