<?php
define('CALL_TYPE_FIRST_LET_INVITER', 0);
define('CALL_TYPE_FIRST_LET_INVITEE', 1);

define('CALL_RESULT_INIT', 0);
define('CALL_RESULT_1SRLEG_NOANSWER', 1);
define('CALL_RESULT_1SRLEG_ANSWERMACHINE', 2);
define('CALL_RESULT_1SRLEG_ANSWERED', 3);
define('CALL_RESULT_1SRLEG_TO_2NDLEG', 4);
define('CALL_RESULT_2NDLEG_NOANSWER', 5);
define('CALL_RESULT_2NDLEG_ANSWERED', 6);
define('CALL_RESULT_COMPLETE', 7);
