<?php
define('CALL_TYPE_FIRST_CALL_INVITER', 0);
define('CALL_TYPE_FIRST_CALL_INVITEE', 1);

define('CALL_RESULT_INIT', 0);
define('CALL_RESULT_1STLEG_NOANSWER', 1);
define('CALL_RESULT_1STLEG_ANSWERMACHINE', 2);
define('CALL_RESULT_1STLEG_ANSWERED', 3);
define('CALL_RESULT_2NDLEG_NOANSWER', 4);
define('CALL_RESULT_2NDLEG_ANSWERED', 5);
define('CALL_RESULT_COMPLETE', 6);
