<?php
define('CALL_RESULT_CREATE', 0);
define('CALL_RESULT_INIT', 1);
define('CALL_RESULT_COMPLETE', 2);
define('CALL_RESULT_INVITER_ANSWER', 101);
define('CALL_RESULT_INVITER_ANSWERMACHINE', 102);
define('CALL_RESULT_INVITER_NOANSWER', 103);
define('CALL_RESULT_CONFERENCE_TO_INVITEE', 104);
define('CALL_RESULT_INVITEE_ANSWER', 105);
define('CALL_RESULT_INVITEE_NOANSWER', 106);
define('CALL_RESULT_INVITEE_ANSWER', 201);
define('CALL_RESULT_INVITEE_ANSWERMACHINE', 202);
define('CALL_RESULT_INVITEE_NOANSWER', 203);
define('CALL_RESULT_CONFERENCE_TO_INVITER', 204);
define('CALL_RESULT_INVITER_ANSWER', 205);
define('CALL_RESULT_INVITER_NOANSWER', 206);
