<script type="text/javascript" src="<?php echo APP_CTX?>/script/anoncall.js"></script>
<?php $country = $this->country?>
<div id="connecting">
	<h1><?php echo MultiLang::getText("We_are_now_connecting_you", $country)?></h1>
	<br>
</div>
<div id="connected" style="display:none">
	<h1 id="callConnected"><?php echo MultiLang::getText("Call_connected", $country)?></h1>
	<h1 id="callCompleted" style="display:none"><?php echo MultiLang::getText("Call_completed", $country)?></h1><br>
	<div><h2 id="duration">00:00:00</h2></div><br>
	<div id="alertInfo" style="display:none"><h2><?php echo MultiLang::getText("You_will_be_charged_again", $country, $this->minCallBlkDur)?></h2></div>
	<form id="followingFrom" action="<?php echo APP_CTX?>/widget/following/refresh" method="post">
		<input type="hidden" name="callInx" value="<?php echo $this->callInx?>" />
	</form>
</div>
<script type="text/javascript">
var timerWatch = -1;
var timerRefresh = window.setInterval(refreshPage, 5000);

var totalTime = -1;
var minCallBlkDur = 60 * <?php echo $this->minCallBlkDur?>;
var callAlertOffset = <?php echo $this->callAlertOffset?>;

function refreshPage() {
	$("#followingFrom").ajaxSubmit(function(result) {
		if (result.status == 1) {
			$("#connecting").attr("style", "display:none");
			$("#connected").attr("style", "display:block");
			if (totalTime == -1) {
				totalTime = result.totalTime;
			}
			if (timerWatch == -1) {
				timerWatch = window.setInterval(runWatch, 1000);
			}
		} else if (result.status == 2) {
			window.clearInterval(timerRefresh);
			window.clearInterval(timerWatch);
			$("#connecting").attr("style", "display:none");
			$("#connected").attr("style", "display:block");
			$("#callConnected").attr("style", "display:none");
			$("#alertInfo").attr("style", "display:none");
			$("#callCompleted").attr("style", "display:block");
			duration = timestamp2His(result.totalTime);
			$("#duration").html(duration);
		}
	});
}

function runWatch() {
	totalTime ++;
	if (totalTime % minCallBlkDur >= minCallBlkDur - callAlertOffset) {
		$("#alertInfo").attr("style", "display:block");
	} else {
		$("#alertInfo").attr("style", "display:none");
	}
	duration = timestamp2His(totalTime);
	$("#duration").html(duration);
}
</script>
