<?php $country = $_SESSION["country"]?>
<form id="paypalFrom" action="<?php echo APP_CTX?>/widget/following/validate" method="post" onsubmit="submiteAnonCall('#paypalFrom'); return false;">
	<div class="topLong">
		<p style="margin-top: 20px"><span class="form"><?php echo MultiLang::getText("PaypalForm_1", $country)?></span></p>
		<input type="text" name="firstName" tabindex="1" />
		<p class="message">
			<span id="firstNameInvalid" ><?php echo MultiLang::getText("Message_3", $country)?></span>
		</p>
		
		<p><span class="form"><?php echo MultiLang::getText("PaypalForm_2", $country)?></span></p>
		<input type="text" name="lsstName" tabindex="1" />
		<p class="message">
			<span id="lastNameInvalid" ><?php echo MultiLang::getText("Message_4", $country)?></span>
		</p>
		
		<p><span class="form"><?php echo MultiLang::getText("PaypalForm_3", $country)?></span></p>
		<select id="cardType" name="cardType" tabindex="1">
			<option value="visa">Visa</option>
			<option value="mastercard">MasterCard</option>
			<option value="discover">Discover</option>
			<option value="amex">AMEX</option>
		</select>
		<p class="message">
			<span id="cardTypeInvalid" ><?php echo MultiLang::getText("Message_5", $country)?></span>
		</p>
		
		<p><span class="form"><?php echo MultiLang::getText("PaypalForm_4", $country)?></span></p>
		<input type="number" name="cardNumber" onkeypress="inputCheck('[0-9]', event)" maxlength="16" tabindex="1" />
		<p class="message">
			<span id="cardNumberInvalid" ><?php echo MultiLang::getText("Message_6", $country)?></span>
		</p>
		
		<p> <span class="form oneThird"><?php echo MultiLang::getText("PaypalForm_5", $country)?></span>
			<span class="form twoThird"><?php echo MultiLang::getText("PaypalForm_6", $country)?></span>
		</p>
		
		<input type="number" class="oneThird" name="cvv" onkeypress="inputCheck('[0-9]', event)" maxlength="3" tabindex="1" />
		<select id="expMonth" name="expMonth" class="oneThird" tabindex="1">
			<option value="01">01</option>
			<option value="02">02</option>
			<option value="03">03</option>
			<option value="04">04</option>
			<option value="05">05</option>
			<option value="06">06</option>
			<option value="07">07</option>
			<option value="08">08</option>
			<option value="09">09</option>
			<option value="10">10</option>
			<option value="11">11</option>
			<option value="12">12</option>
		</select>
		<select id="expYear" name="expYear" class="oneThird" tabindex="1"></select>
		<p class="message">
			<span id="cvvInvalid" ><?php echo MultiLang::getText("Message_7", $country)?></span>
			<span id="expDateInvalid" ><?php echo MultiLang::getText("Message_8", $country)?></span>
		</p>
	</div>

	<input style="margin-top: 20px" type="submit" value="<?php echo MultiLang::getText("PaypalForm_7", $country)?>" />
</form>
<script type="text/javascript">
$("#cardType").prop("selectedIndex", -1);
$("#expMonth").prop("selectedIndex", -1);

var today = new Date();
var yyyy = today.getFullYear();
for (var i = 0; i < 5; i ++) {
	var year = yyyy + i;
	$("#expYear").append("<option value=" + year + ">" + year + "</option>");
}
$("#expYear").prop("selectedIndex", -1);
</script>
