<?php $country = $_SESSION["country"]?>
<p style="margin-top: 20px"><span class="h2"><?php echo MultiLang::getText("ThankYou_1", $country)?></span></p>
<form style="margin-top: 40px" id="paypalFrom" action="<?php echo APP_CTX?>/widget/following/connecting" method="post">
	<input type="submit" value="<?php echo MultiLang::getText("ThankYou_2", $country)?>" />
</form>
<p style="margin-top: 60px">
	<span class="oneThird red"><?php echo $this->woman?></span>
	<span class="middle red"></span>
	<span class="oneThird red"><?php echo $this->man?></span>
</p>
<div style="margin-top: 10px" class="_idGenObjectLayout-1">
	<div class="_idGenPageitem-6"><p><span class="caption_cloud_small"></span></p></div>
</div>